# -*- coding: utf-8 -*-
"""Reporte_NoK_con_ZIP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16pB889Ar5bC71JH3AMOo6vrwbbpaLTmX
"""

!pip install pdfplumber pandas openpyxl

# ============================================================
# CARGA DE ARCHIVOS: PDF y ZIP
# ============================================================
# Puedes seleccionar:
#   - uno o varios PDF
#   - uno o varios ZIP que contengan PDF
#   - ZIP dentro de ZIP (hasta 5 niveles)
#
# Los PDF se cargan en memoria; no es necesario extraerlos
# manualmente antes de ejecutar el procesamiento.
# ============================================================

from google.colab import files
import io
import zipfile
from pathlib import PurePosixPath

uploaded = files.upload()

# Diccionario final que utiliza la celda principal de procesamiento.
# La clave es el nombre del PDF y el valor son sus bytes.
pdf_files = {}
zip_files_found = 0
ignored_files = []

MAX_ZIP_DEPTH = 5

def add_zip_contents(zip_bytes, source_name="archivo.zip", depth=0):
    """Extrae PDF de un ZIP y también busca ZIP anidados."""
    global zip_files_found

    if depth > MAX_ZIP_DEPTH:
        print(f"⚠️ Se alcanzó el máximo de ZIP anidados en: {source_name}")
        return

    try:
        with zipfile.ZipFile(io.BytesIO(zip_bytes), "r") as z:
            for info in z.infolist():
                if info.is_dir():
                    continue

                # Normalizar la ruta interna del ZIP
                safe_name = str(PurePosixPath(info.filename))
                suffix = PurePosixPath(safe_name).suffix.lower()

                try:
                    content = z.read(info)
                except Exception as e:
                    print(f"⚠️ No se pudo leer '{safe_name}' dentro de {source_name}: {e}")
                    continue

                if suffix == ".pdf":
                    # Usamos la ruta interna como nombre para evitar colisiones.
                    pdf_name = f"{source_name}::{safe_name}"

                    # Si hubiera nombres repetidos, agregar consecutivo.
                    base_name = pdf_name
                    counter = 2
                    while pdf_name in pdf_files:
                        stem = PurePosixPath(base_name).stem
                        parent = str(PurePosixPath(base_name).parent)
                        if parent == ".":
                            pdf_name = f"{stem}_{counter}.pdf"
                        else:
                            pdf_name = f"{parent}/{stem}_{counter}.pdf"
                        counter += 1

                    pdf_files[pdf_name] = content

                elif suffix == ".zip":
                    zip_files_found += 1
                    add_zip_contents(
                        content,
                        source_name=f"{source_name}::{safe_name}",
                        depth=depth + 1
                    )

    except zipfile.BadZipFile:
        print(f"⚠️ El archivo '{source_name}' no es un ZIP válido.")
    except Exception as e:
        print(f"⚠️ Error procesando ZIP '{source_name}': {e}")


# Procesar los archivos seleccionados.
for filename, content in uploaded.items():
    suffix = PurePosixPath(filename).suffix.lower()

    if suffix == ".pdf":
        pdf_files[filename] = content

    elif suffix == ".zip":
        zip_files_found += 1
        add_zip_contents(content, source_name=filename)

    else:
        ignored_files.append(filename)

# IMPORTANTE:
# La celda principal existente usa "uploaded", así que conservamos
# ese nombre y le pasamos únicamente los PDF ya listos para procesar.
uploaded = pdf_files

print("\n" + "=" * 60)
print("RESUMEN DE CARGA")
print("=" * 60)
print(f"Archivos PDF listos para procesar: {len(uploaded)}")
print(f"Archivos ZIP seleccionados/detectados: {zip_files_found}")

if ignored_files:
    print(f"Archivos ignorados (no son PDF/ZIP): {len(ignored_files)}")
    for name in ignored_files:
        print(f"  - {name}")

if uploaded:
    print("\nPDF que serán procesados:")
    for i, filename in enumerate(uploaded.keys(), start=1):
        print(f"{i:>3}. {filename}")
else:
    print("\n⚠️ No se encontraron PDF para procesar.")

print("=" * 60)

"""### Resumen de Valores Anormales e Identificación de Riesgos en el Proceso

Basado en el análisis detallado de las principales características 'Nok', podemos observar lo siguiente:

*   **Distribución de Mediciones:** Los histogramas muestran la distribución general de las mediciones para cada característica. Si las mediciones 'Nok' se concentran en uno de los extremos de la distribución o forman un grupo separado, esto podría indicar una desviación sistemática en el proceso (ej., herramienta desgastada, calibración incorrecta, etc.).

*   **Valores Atípicos (Outliers):** Los gráficos de valores individuales permiten identificar rápidamente mediciones 'Nok' que están muy alejadas del resto de la población. Estos puntos pueden ser indicativos de eventos aislados, errores de medición o problemas puntuales en piezas específicas.

*   **Concentración por Ubicación (Leva/Apoyo):** El desglose por Leva/Apoyo para las características 'Nok' es crucial. Si una característica 'Nok' se concentra consistentemente en una Leva o Apoyo particular, esto sugiere un problema localizado en esa sección de la pieza o en la estación de trabajo/herramienta que la procesa.

*   **Tiempos de Rechazo:** La información temporal puede utilizarse para identificar tendencias de rechazo y priorizar revisiones del proceso.

*   **Entrada de datos:** El programa admite ahora PDF individuales y archivos ZIP con PDF, incluyendo ZIP anidados.

Este análisis forma parte del procesamiento automático del reporte de mediciones.

### Procesando Múltiples Archivos PDF y ZIP

La carga de archivos ahora acepta:

- **PDF individuales**
- **ZIP con uno o varios PDF**
- **ZIP dentro de ZIP** (hasta 5 niveles)

Los PDF encontrados dentro de los ZIP se extraen automáticamente en memoria y se envían a la misma lógica de procesamiento que ya utiliza el programa.

El proceso conserva la extracción de:

1. **MAIN JOURNALS** y **LOBES**
2. **CHATTER: Base Circle** y **CHATTER: Lift Area**
3. **CHATTER: Journals**
4. Consolidación en Excel: **Apoyos, Levas, chatter Levas, Chatter apoyos, Nok, Analisis_Resumen y Analisis_Detallado_NOK**

Al finalizar se genera `data.xlsx`.
"""

import pdfplumber
import pandas as pd
import re
import numpy as np
import io # Import the io module

# Helper function to determine 'Resultado'
def get_resultado(value_str, characteristic_name=None):
    # First, check for '#' which always indicates 'Nok'
    if '#' in str(value_str):
        return 'Nok'

    # Specific threshold for chatter in 'Reg 5 UPR de 300 a 400'
    CHATTER_NOK_THRESHOLD = 0.00008
    if characteristic_name in ['(5) 301-400 UPR', '(9) 301-400 UPR']:
        try:
            # Convert to float for comparison. Handle potential comma decimal separator.
            numeric_val = float(str(value_str).replace(',', '.'))
            if numeric_val > CHATTER_NOK_THRESHOLD:
                return 'Nok'
        except ValueError:
            # If conversion to float fails, it's not a numeric value for comparison.
            pass
    return 'Ok'

# Define the lists for 'Caracteristica' and 'Apoyo' as per your request (re-defined)
characteristics_for_columns = ['Diametro', 'Roundness', 'Runout', 'Concentricity', 'Parallelism', 'Taper', 'Cylindricity']
apoyo_identifiers = ['Aux:G', '1:A L', '1:A R', '2:C', '3:D', '4:E', '5:B']
chatter_apoyos_characteristics = [
    '(1) 5 - 8 UPR',
    '(2) 9 - 15 UPR',
    '(3) 16 - 23 UPR',
    '(4) 24 - 28 UPR',
    '(5) 29- 45 UPR',
    '(6) 46-70 UPR',
    '(7) 71-140 UPR',
    '(8) 141-215 UPR' # Removed '(9) 301-400 UPR' as it's not in the PDF text for Journals
]
# Define the mapping for 'Apoyo' values (re-defined)
apoyo_rename_mapping = {
    '1:': '1:A L',
    '2:': '1:A R',
    '3:': '2:C',
    '4:': '3:D',
    '5:': '4:E',
    '6:': '5:B'
}
chatter_characteristics = ['(1) 40- 80 UPR', '(2) 81-140 UPR', '(3) 141-190 UPR', '(4) 191-300 UPR', '(5) 301-400 UPR'] # Added new characteristic
chatter_areas = ['Base Circle', 'Lift Area']

# CHATTER_NOK_THRESHOLD is now handled inside get_resultado function conditionally

# Lists to collect DataFrames from all files
all_apoyos_dfs = [] # Changed from all_melted_dfs
all_levas_dfs = [] # New list for Levas data
all_chatter_lobes_dfs = []
all_chatter_apoyos_dfs = []

# Initialize file_consecutive_number outside the loop
file_consecutive_number = 0

# Iterate through all uploaded PDF files
for pdf_filename in uploaded.keys():
    file_consecutive_number += 1 # Increment for each new file
    print(f"\nProcessing file: {pdf_filename} (Pieza: {file_consecutive_number})")

    first_page_text = ""
    second_page_text = ""

    # Open the PDF and extract text from pages
    try:
        # Wrap the bytes object in io.BytesIO
        with pdfplumber.open(io.BytesIO(uploaded[pdf_filename])) as pdf:
            if pdf.pages:
                first_page_text = pdf.pages[0].extract_text()
                if len(pdf.pages) > 1:
                    second_page_text = pdf.pages[1].extract_text()
                else:
                    print(f"Warning: File {pdf_filename} has only one page. No second page data for 'Chatter apoyos'.")
            else:
                print(f"Error: File {pdf_filename} has no pages. Skipping.")
                continue
    except pdfplumber.pdf.PdfminerException as e: # Corrected exception type
        print(f"Error processing PDF file {pdf_filename}: {e}. Skipping this file.")
        continue
    except Exception as e:
        print(f"An unexpected error occurred while processing PDF file {pdf_filename}: {e}. Skipping this file.")


    # --- Extraction logic for MAIN JOURNALS (for df_apoyos_final) ---
    apoyos_data_rows_current_file = [] # Renamed from data_rows_current_file
    main_journals_start = first_page_text.find('MAIN JOURNALS:')
    lobes_start = first_page_text.find('LOBES:')
    chatter_start = first_page_text.find('CHATTER:')

    if main_journals_start != -1 and lobes_start != -1:
        main_journals_text = first_page_text[main_journals_start:lobes_start]

        main_journals_headers_pdf = ['Measured Diameter', 'Error', 'Roundness', 'Runout', 'Concentricity', 'Parallelism', 'Taper', 'Cylindricity']

        char_mapping = {
            'Error': 'Diametro',
            'Roundness': 'Roundness',
            'Runout': 'Runout',
            'Concentricity': 'Concentricity',
            'Parallelism': 'Parallelism',
            'Taper': 'Taper',
            'Cylindricity': 'Cylindricity'
        }

        main_journals_pattern = re.compile(r'(' + '|'.join(re.escape(i) for i in apoyo_identifiers) + r')\s+([\s\d.\-#]+(?:\s+J[\d\-]+:\s+[\d.\-]+)?(?:\s+L[\d\-]+:\s+[\d.\-]+)?(?:\s+Tol:\s+[\d.\-]+)?)')

        lines = main_journals_text.split('\n')
        for line in lines:
            match = main_journals_pattern.match(line.strip())
            if match:
                apoyo_val = match.group(1).strip()
                values_str = match.group(2).strip()
                raw_values = [v for v in re.split(r'\s+', values_str) if v and not re.match(r'J\d-\d:|J\d:', v) and v != 'Tol:']
                extracted_data_for_row = {char: None for char in characteristics_for_columns}

                if apoyo_val == '1:A L':
                    if len(raw_values) >= 6:
                        extracted_data_for_row['Diametro'] = raw_values[1]
                        extracted_data_for_row['Roundness'] = raw_values[2]
                        extracted_data_for_row['Runout'] = raw_values[3]
                        extracted_data_for_row['Concentricity'] = raw_values[4]
                        extracted_data_for_row['Taper'] = raw_values[5]
                elif apoyo_val == '5:B':
                    if len(raw_values) >= 7:
                        extracted_data_for_row['Diametro'] = raw_values[1]
                        extracted_data_for_row['Roundness'] = raw_values[2]
                        extracted_data_for_row['Runout'] = raw_values[3]
                        extracted_data_for_row['Concentricity'] = raw_values[4]
                        extracted_data_for_row['Taper'] = raw_values[5]
                        extracted_data_for_row['Cylindricity'] = raw_values[6]
                else:
                    current_raw_value_index = 0
                    for pdf_header_name in main_journals_headers_pdf:
                        if pdf_header_name == 'Measured Diameter':
                            if current_raw_value_index < len(raw_values):
                                current_raw_value_index += 1
                            continue
                        if pdf_header_name in char_mapping:
                            char_name = char_mapping[pdf_header_name]
                            if char_name in characteristics_for_columns:
                                if current_raw_value_index < len(raw_values):
                                    extracted_data_for_row[char_name] = raw_values[current_raw_value_index]
                                current_raw_value_index += 1
                            else:
                                 if current_raw_value_index < len(raw_values):
                                    current_raw_value_index += 1
                        else:
                              if current_raw_value_index < len(raw_values):
                                current_raw_value_index += 1

                for char_name_in_df in characteristics_for_columns:
                    medicion_val = extracted_data_for_row.get(char_name_in_df)
                    if medicion_val is not None:
                        # For MAIN JOURNALS, only check for '#' flag
                        resultado_val = get_resultado(str(medicion_val))
                        apoyos_data_rows_current_file.append({
                            'Nombre del archivo': pdf_filename,
                            'Pieza': file_consecutive_number,
                            'Leva': None,
                            'Apoyo': apoyo_val,
                            'Caracteristica': char_name_in_df,
                            'Medicion': str(medicion_val).replace('#', ''),
                            'Area': 'Apoyos', # MODIFICADO: Se establece 'Apoyos' en la columna 'Area'
                            'Resultado': resultado_val
                        })

    # --- Extraction logic for LOBES (for df_levas_final) ---
    levas_data_rows_current_file = [] # New list
    if lobes_start != -1:
        lobes_text = first_page_text[lobes_start:chatter_start if chatter_start != -1 else len(first_page_text)]
        lobes_headers = ['AngleErr', "BC-Rad'sErr", 'BC-Runout', 'BC-Vel./10°', 'Ramp-MaxLift', 'Nose-MaxLift', 'Ramp+9°Vel/1°', 'Nose-Vel./1°', 'Taper', 'Center-Dev']
        lobes_line_pattern = re.compile(r'^(\d+:\s[A-Z]+-\d+)\s+(.*)')

        lines = lobes_text.split('\n')
        data_lines_start_index = -1
        for i, line in enumerate(lines):
            if line.strip().startswith('1: EXH-1'):
                data_lines_start_index = i
                break

        if data_lines_start_index != -1:
            for line_idx, line in enumerate(lines[data_lines_start_index:]):
                stripped_line = line.strip()
                match = lobes_line_pattern.match(stripped_line)
                if match:
                    leva_val = match.group(1).strip()
                    values_str = match.group(2).strip()
                    raw_values = [v for v in re.split(r'\s+', values_str) if v]

                    processed_values = []
                    if len(raw_values) == len(lobes_headers):
                        processed_values = raw_values
                    elif len(raw_values) == 2 * len(lobes_headers):
                        processed_values = [raw_values[j] for j in range(0, len(raw_values), 2)]
                    else:
                        continue

                    for i, char_name in enumerate(lobes_headers):
                        if i < len(processed_values):
                            medicion_val = processed_values[i]
                            # For LOBES, only check for '#' flag
                            resultado_val = get_resultado(medicion_val)
                            levas_data_rows_current_file.append({ # Appended to levas_data_rows_current_file
                                'Nombre del archivo': pdf_filename,
                                'Pieza': file_consecutive_number,
                                'Leva': leva_val,
                                'Apoyo': None,
                                'Caracteristica': char_name,
                                'Medicion': medicion_val.replace('#', ''),
                                'Area': 'Levas', # MODIFICADO: Se establece 'Levas' en la columna 'Area'
                                'Resultado': resultado_val
                            })

    # Process collected data for the current file
    df_apoyos_current_file = pd.DataFrame(apoyos_data_rows_current_file)
    if not df_apoyos_current_file.empty:
        df_apoyos_current_file['Medicion'] = pd.to_numeric(df_apoyos_current_file['Medicion'], errors='coerce')
    all_apoyos_dfs.append(df_apoyos_current_file)

    df_levas_current_file = pd.DataFrame(levas_data_rows_current_file)
    if not df_levas_current_file.empty:
        df_levas_current_file['Medicion'] = pd.to_numeric(df_levas_current_file['Medicion'], errors='coerce')
    all_levas_dfs.append(df_levas_current_file)

    # --- Extraction logic for CHATTER LEVAS ---
    chatter_data_rows_current_file = []
    if chatter_start != -1:
        chatter_text = first_page_text[chatter_start:]
        chatter_lines = chatter_text.split('\n')
        chatter_data_start_idx = -1
        for i, line in enumerate(chatter_lines):
            # Updated regex to match lines starting with a number followed by a colon (e.g., '1:')
            if re.match(r'^\s*\d+:', line.strip()):
                chatter_data_start_idx = i
                break
        # print(f"[DEBUG CHATTER LEVAS] chatter_data_start_idx: {chatter_data_start_idx}") # Removed debug print

        if chatter_data_start_idx != -1:
            for line_num, line in enumerate(chatter_lines[chatter_data_start_idx:]):
                stripped_line = line.strip()
                # print(f"[DEBUG CHATTER LEVAS] Processing line: {stripped_line[:50]}...") # Removed debug print
                # Updated regex to capture the number as leva_val
                match = re.match(r'^(\d+):\s+(.*)', stripped_line)
                if match:
                    # print(f"[DEBUG CHATTER LEVAS] Matched line: {stripped_line[:50]}...") # Removed debug print
                    leva_val = match.group(1).strip() # Will be '1', '2', etc.
                    values_str = match.group(2).strip()
                    raw_values = [v for v in re.split(r'\s+', values_str) if v]

                    # Updated logic for 5 characteristics (5 * 2 values for BC, 5 * 2 values for LA = 20 total raw_values)
                    if len(raw_values) == len(chatter_characteristics) * 2 * 2:
                        num_chatter_chars = len(chatter_characteristics)
                        amplitudes_bc = [raw_values[i * 2] for i in range(num_chatter_chars)]
                        amplitudes_la = [raw_values[num_chatter_chars * 2 + i * 2] for i in range(num_chatter_chars)]

                        for i, char_name in enumerate(chatter_characteristics):
                            medicion_val = amplitudes_bc[i]
                            # Pass characteristic_name to get_resultado for conditional threshold application
                            resultado_val = get_resultado(medicion_val, characteristic_name=char_name)
                            chatter_data_rows_current_file.append({
                                'Nombre del archivo': pdf_filename,
                                'Pieza': file_consecutive_number,
                                'Leva': leva_val,
                                'Apoyo': None,
                                'Caracteristica': char_name,
                                'Medicion': medicion_val.replace('#', ''),
                                'Area': 'Base Circle',
                                'Resultado': resultado_val
                            })
                        for i, char_name in enumerate(chatter_characteristics):
                            medicion_val = amplitudes_la[i]
                            # Pass characteristic_name to get_resultado for conditional threshold application
                            resultado_val = get_resultado(medicion_val, characteristic_name=char_name)
                            chatter_data_rows_current_file.append({
                                'Nombre del archivo': pdf_filename,
                                'Pieza': file_consecutive_number,
                                'Leva': leva_val,
                                'Apoyo': None,
                                'Caracteristica': char_name,
                                'Medicion': medicion_val.replace('#', ''),
                                'Area': 'Lift Area',
                                'Resultado': resultado_val
                            })
    df_chatter_lobes_current_file = pd.DataFrame(chatter_data_rows_current_file)
    if not df_chatter_lobes_current_file.empty:
        df_chatter_lobes_current_file['Medicion'] = pd.to_numeric(df_chatter_lobes_current_file['Medicion'], errors='coerce')
    all_chatter_lobes_dfs.append(df_chatter_lobes_current_file)

    # --- Extraction logic for CHATTER APYOS ---
    chatter_apoyos_data_rows_current_file = []
    if second_page_text:
        chatter_journals_start = second_page_text.find('CHATTER: ------------------------- Journals --------------------------')
        if chatter_journals_start != -1:
            chatter_journals_text = second_page_text[chatter_journals_start:]
            chatter_journals_lines = chatter_journals_text.split('\n')
            chatter_journals_data_start_idx = -1
            for i, line in enumerate(chatter_journals_lines):
                if re.match(r'^\s*\d+:', line.strip()):
                    chatter_journals_data_start_idx = i
                    break

            if chatter_journals_data_start_idx != -1:
                for line in chatter_journals_lines[chatter_journals_data_start_idx:]:
                    stripped_line = line.strip()
                    match = re.match(r'^(\d+):\s+(.*)', stripped_line)

                    if match:
                        apoyo_val_original = match.group(1).strip()
                        apoyo_val_mapped = apoyo_rename_mapping.get(apoyo_val_original, apoyo_val_original)
                        values_str = match.group(2).strip()

                        raw_values = [v for v in re.split(r'\s+', values_str) if v]

                        # Updated logic for 8 characteristics (8 * 2 values = 16 total raw_values)
                        if len(raw_values) == len(chatter_apoyos_characteristics) * 2:
                            amplitudes = [raw_values[j] for j in range(0, len(raw_values), 2)]
                            for i, char_name in enumerate(chatter_apoyos_characteristics):
                                medicion_val = amplitudes[i]
                                # Pass characteristic_name to get_resultado for conditional threshold application
                                resultado_val = get_resultado(medicion_val, characteristic_name=char_name)
                                chatter_apoyos_data_rows_current_file.append({
                                    'Nombre del archivo': pdf_filename,
                                    'Pieza': file_consecutive_number,
                                    'Leva': None,
                                    'Apoyo': apoyo_val_mapped,
                                    'Caracteristica': char_name,
                                    'Medicion': medicion_val.replace('#', ''),
                                    'Area': 'Apoyos', # MODIFICADO: Se cambia 'Journals' a 'Apoyos'
                                    'Resultado': resultado_val
                                })
    df_chatter_apoyos_current_file = pd.DataFrame(chatter_apoyos_data_rows_current_file)
    if not df_chatter_apoyos_current_file.empty:
        df_chatter_apoyos_current_file['Medicion'] = pd.to_numeric(df_chatter_apoyos_current_file['Medicion'], errors='coerce')
    all_chatter_apoyos_dfs.append(df_chatter_apoyos_current_file)

# --- Concatenate all collected DataFrames after processing all files ---

df_apoyos_final = pd.concat(all_apoyos_dfs, ignore_index=True) if all_apoyos_dfs else pd.DataFrame() # Renamed and directly uses all_apoyos_dfs
print(f"Shape of df_apoyos_final: {df_apoyos_final.shape}")

df_levas_final = pd.concat(all_levas_dfs, ignore_index=True) if all_levas_dfs else pd.DataFrame() # New df_levas_final
print(f"Shape of df_levas_final: {df_levas_final.shape}")

df_chatter_lobes_final = pd.concat(all_chatter_lobes_dfs, ignore_index=True) if all_chatter_lobes_dfs else pd.DataFrame()
print(f"Shape of df_chatter_lobes_final: {df_chatter_lobes_final.shape}")
df_chatter_apoyos_final = pd.concat(all_chatter_apoyos_dfs, ignore_index=True) if all_chatter_apoyos_dfs else pd.DataFrame()
print(f"Shape of df_chatter_apoyos_final: {df_chatter_apoyos_final.shape}")

# Remove original df_lobes_final creation as it's now df_levas_final
# df_lobes_final = df_melted_final[df_melted_final['Leva'].notna()].copy()
# df_lobes_final['Apoyo'] = None
# print(f"Shape of df_lobes_final: {df_lobes_final.shape}")

# Create df_master by concatenating all final DataFrames
df_master = pd.concat([
    df_apoyos_final,          # Changed from df_melted_final
    df_levas_final,           # Changed from df_lobes_final
    df_chatter_lobes_final,   # Contains Chatter Lobes
    df_chatter_apoyos_final   # Contains Chatter Apoyos
], ignore_index=True)
print(f"Shape of df_master: {df_master.shape}")

# Create df_nok by filtering df_master
df_nok = df_master[df_master['Resultado'] == 'Nok'].copy()
print(f"Shape of df_nok: {df_nok.shape}")

# --- Calculate summary statistics for 'Analisis_Resumen' ---
total_pieces_analyzed = df_master['Pieza'].nunique()
pieces_with_nok = df_nok['Pieza'].unique()
num_nok_pieces = len(pieces_with_nok)
pieces_with_ok = df_master[~df_master['Pieza'].isin(pieces_with_nok)]['Pieza'].unique()
num_ok_pieces = len(pieces_with_ok)
total_characteristics = len(df_master)
num_ok_characteristics = len(df_master[df_master['Resultado'] == 'Ok'])
num_nok_characteristics = len(df_nok)
rejection_percentage = (num_nok_pieces / total_pieces_analyzed) * 100 if total_pieces_analyzed > 0 else 0
ftq = (num_ok_pieces / total_pieces_analyzed) * 100 if total_pieces_analyzed > 0 else 0
pct_ok_characteristics = (num_ok_characteristics / total_characteristics) * 100 if total_characteristics > 0 else 0
pct_nok_characteristics = (num_nok_characteristics / total_characteristics) * 100 if total_characteristics > 0 else 0
specific_nok_char_to_check = '(5) 301-400 UPR'
pieces_rejected_by_specific_nok_char = df_nok[df_nok['Caracteristica'] == specific_nok_char_to_check]['Pieza'].unique()
count_pieces_only_this_nok_char = 0
for piece_id in pieces_rejected_by_specific_nok_char:
    nok_chars_for_this_piece = df_nok[df_nok['Pieza'] == piece_id]['Caracteristica'].unique()
    if len(nok_chars_for_this_piece) == 1 and nok_chars_for_this_piece[0] == specific_nok_char_to_check:
        count_pieces_only_this_nok_char += 1
count_pieces_with_specific_nok_and_others = 0
for piece_id in pieces_rejected_by_specific_nok_char:
    nok_chars_for_this_piece = df_nok[df_nok['Pieza'] == piece_id]['Caracteristica'].unique()
    if specific_nok_char_to_check in nok_chars_for_this_piece and len(nok_chars_for_this_piece) > 1:
        count_pieces_with_specific_nok_and_others += 1
analysis_data = {
    'Metrica': [
        'Total de piezas analizadas',
        'Piezas con resultado OK (todas las caracteristicas OK)',
        'Piezas con resultado NOK (al menos una caracteristica NOK)',
        'Porcentaje de Rechazo',
        'FTQ (First Time Quality)',
        'Total de características analizadas',
        'Características con resultado OK',
        'Características con resultado NOK',
        '% Características OK',
        '% Características NOK',
        f'Cantidad piezas rechazadas SOLO por "{specific_nok_char_to_check}"',
        f'Cantidad piezas rechazadas por "{specific_nok_char_to_check}" Y alguna otra característica'
    ],
    'Valor': [
        total_pieces_analyzed,
        num_ok_pieces,
        num_nok_pieces,
        f'{rejection_percentage:.2f}%',
        f'{ftq:.2f}%',
        total_characteristics,
        num_ok_characteristics,
        num_nok_characteristics,
        f'{pct_ok_characteristics:.2f}%',
        f'{pct_nok_characteristics:.2f}%',
        count_pieces_only_this_nok_char,
        count_pieces_with_specific_nok_and_others
    ]
}
df_analysis = pd.DataFrame(analysis_data)

# --- Calculate detailed NOK characteristics for 'Analisis_Detallado_NOK' ---
nok_characteristics_counts = df_nok['Caracteristica'].value_counts().reset_index()
nok_characteristics_counts.columns = ['Caracteristica', 'Cantidad_NOK']
top_5_nok_characteristics = nok_characteristics_counts['Caracteristica'].head(15).tolist()
detailed_analysis_results = []
def extract_time_from_filename(filename):
    parts = filename.split('_')
    if len(parts) >= 3:
        time_part_raw = parts[-2]
        time_part = time_part_raw.split(' ')[0]
        return 'N/A'
    return 'N/A'

for char in top_5_nok_characteristics:
    df_char_all = df_master[df_master['Caracteristica'] == char].copy()
    df_char_nok = df_nok[df_nok['Caracteristica'] == char].copy()

    if df_char_all.empty:
        continue

    num_pieces_with_nok = df_char_nok['Pieza'].nunique() if not df_char_nok.empty else 0
    avg_total_medicion = df_char_all['Medicion'].mean()
    std_total_medicion = df_char_all['Medicion'].std()
    avg_nok_medicion = df_char_nok['Medicion'].mean() if not df_char_nok.empty else float('nan')
    std_nok_medicion = df_char_nok['Medicion'].std() if not df_char_nok.empty else float('nan')
    max_nok_medicion = df_char_nok['Medicion'].max() if not df_char_nok.empty else float('nan')
    min_nok_medicion = df_char_nok['Medicion'].min() if not df_char_nok.empty else float('nan')

    detailed_analysis_results.append({
        'Caracteristica': char,
        'Cantidad Piezas NOK': num_pieces_with_nok,
        'Promedio Total Med.': f'{avg_total_medicion:.4f}' if pd.notna(avg_total_medicion) else 'N/A',
        'Std Total Med.': f'{std_total_medicion:.4f}' if pd.notna(std_total_medicion) else 'N/A',
        'Promedio NOK Med.': f'{avg_nok_medicion:.4f}' if pd.notna(avg_nok_medicion) else 'N/A',
        'Std NOK Med.': f'{std_nok_medicion:.4f}' if pd.notna(std_nok_medicion) else 'N/A',
        'Max NOK Med.': f'{max_nok_medicion:.4f}' if pd.notna(max_nok_medicion) else 'N/A',
        'Min NOK Med.': f'{min_nok_medicion:.4f}' if pd.notna(min_nok_medicion) else 'N/A'
    })
df_detailed_analysis_summary = pd.DataFrame(detailed_analysis_results)


# --- Save all DataFrames to respective sheets in data.xlsx and data_part2.xlsx ---
output_excel_filename = "data.xlsx"
output_excel_filename_part2 = "data_part2.xlsx" # New filename for the second part

# Crucial correction for MAX_ROWS_PER_SHEET (1,048,576 total rows - 1 header row)
MAX_ROWS_PER_SHEET = 1048576 - 1

# Prepare DataFrames and sheet names for data.xlsx
dfs_to_write_to_data_xlsx = []
df_levas_second_file = None # To store df_levas_part2 if created

if not df_apoyos_final.empty:
    dfs_to_write_to_data_xlsx.append((df_apoyos_final, 'Apoyos'))

if not df_levas_final.empty:
    if len(df_levas_final) > MAX_ROWS_PER_SHEET:
        print(f"'df_levas_final' is too large ({len(df_levas_final)} rows). Splitting into two files.")
        df_levas_part1 = df_levas_final.iloc[0:MAX_ROWS_PER_SHEET].copy() # .copy() to avoid SettingWithCopyWarning
        df_levas_part2 = df_levas_final.iloc[MAX_ROWS_PER_SHEET:].copy() # .copy() to avoid SettingWithCopyWarning
        dfs_to_write_to_data_xlsx.append((df_levas_part1, 'Levas')) # First part goes to data.xlsx
        df_levas_second_file = df_levas_part2 # Second part stored for data_part2.xlsx
    else:
        dfs_to_write_to_data_xlsx.append((df_levas_final, 'Levas'))

if not df_chatter_lobes_final.empty:
    dfs_to_write_to_data_xlsx.append((df_chatter_lobes_final, 'chatter Levas'))

if not df_chatter_apoyos_final.empty:
    dfs_to_write_to_data_xlsx.append((df_chatter_apoyos_final, 'Chatter apoyos'))

if not df_master.empty:
    # No need to write df_master to Excel, it's used for analysis and NOK filtering
    pass # dfs_to_write_to_data_xlsx.append((df_master, 'Master')) # Original logic was not adding master

if not df_nok.empty:
    dfs_to_write_to_data_xlsx.append((df_nok, 'Nok'))

if not df_analysis.empty:
    dfs_to_write_to_data_xlsx.append((df_analysis, 'Analisis_Resumen'))

if not df_detailed_analysis_summary.empty:
    dfs_to_write_to_data_xlsx.append((df_detailed_analysis_summary, 'Analisis_Detallado_NOK'))


# Write all DataFrames to data.xlsx in a single block
if dfs_to_write_to_data_xlsx:
    with pd.ExcelWriter(output_excel_filename, engine='openpyxl', mode='w') as writer:
        for df_to_write, sheet_name in dfs_to_write_to_data_xlsx:
            df_to_write.to_excel(writer, index=False, sheet_name=sheet_name)
            print(f"Hoja '{sheet_name}' añadida/actualizada exitosamente en {output_excel_filename}.")
else:
    print(f"No hay DataFrames para escribir en '{output_excel_filename}'.")


# Write df_levas_part2 to a separate file if it exists
if df_levas_second_file is not None and not df_levas_second_file.empty:
    with pd.ExcelWriter(output_excel_filename_part2, engine='openpyxl', mode='w') as writer_part2:
        df_levas_second_file.to_excel(writer_part2, index=False, sheet_name='Levas_Parte_2')
        print(f"Hoja 'Levas_Parte_2' añadida exitosamente en {output_excel_filename_part2}.")
else:
    if df_levas_second_file is not None: # Meaning it was supposed to be created but was empty
        print(f"El DataFrame para '{output_excel_filename_part2}' estaba vacío, no se creó el archivo.")
    else: # Meaning no second file needed
        pass # No second file needed

print(f"\nTodos los datos consolidados y guardados en los archivos Excel.")

# --- Verification step: Read data.xlsx back and confirm unique 'Pieza' values ---
try:
    # Read the 'Apoyos' sheet from the newly created Excel file
    df_verify = pd.read_excel(output_excel_filename, sheet_name='Apoyos') # Read 'Apoyos' or another sheet instead of 'Master'
    unique_piezas = df_verify['Pieza'].nunique()
    print(f"\nVERIFICACIÓN: El archivo '{output_excel_filename}' (hoja 'Apoyos') contiene datos para {unique_piezas} 'Piezas' únicas.")
except Exception as e:
    print(f"\nERROR durante la verificación del archivo Excel: {e}")

# Vista rápida del primer PDF listo para procesamiento
if not uploaded:
    print("No hay PDF disponibles para inspeccionar.")
else:
    pdf_filename = next(iter(uploaded))
    print(f"PDF seleccionado para inspección: {pdf_filename}")

    with pdfplumber.open(io.BytesIO(uploaded[pdf_filename])) as pdf:
        first_page_text = pdf.pages[0].extract_text()
        print("\n--- First page text of the PDF ---")
        print(first_page_text)
        print("----------------------------------")

        tables = pdf.pages[0].extract_tables()
        if tables:
            print("\n--- Tables found on the first page ---")
            for i, table in enumerate(tables):
                print(f"Table {i+1} (rows: {len(table)}, cols: {len(table[0]) if table else 0}):")
                for row_idx, row in enumerate(table):
                    if row_idx < 5:
                        print(row)
                    elif row_idx == 5:
                        print("...")
                print("----------------------------------")
        else:
            print("\nNo tables found on the first page.")

import io

# Open the PDF and extract text from the first page for initial inspection
with pdfplumber.open(io.BytesIO(uploaded[pdf_filename])) as pdf:
    first_page_text = pdf.pages[0].extract_text()
    print("\n--- First page text of the PDF ---")
    print(first_page_text)
    print("----------------------------------")

    # Enable table extraction to inspect table structures
    tables = pdf.pages[0].extract_tables()
    if tables:
        print("\n--- Tables found on the first page ---")
        for i, table in enumerate(tables):
            print(f"Table {i+1} (rows: {len(table)}, cols: {len(table[0]) if table else 0}):")
            for row_idx, row in enumerate(table):
                if row_idx < 5: # Print first 5 rows to avoid too much output
                    print(row)
                elif row_idx == 5:
                    print("...")
            print("----------------------------------")
    else:
        print("\nNo tables found on the first page.")

"""The previous cell output shows the text content of the first page of your PDF. Based on this, you would need to write specific logic to extract `Leva`, `Area`, `Resultado`, and map them to `Caracteristica`, `Medicion`, and `Apoyo` columns. Below is a placeholder code that demonstrates how to construct the final DataFrame and save it to Excel, using the `characteristics_for_columns` and `apoyo_identifiers` you provided. You will need to customize the data extraction part (`# TODO: Extract actual data from PDF`) based on the PDF's structure.

To accurately extract the data, we'll use regular expressions to locate and parse the `MAIN JOURNALS` and `LOBES` sections from the `first_page_text`.

### **Parsing Strategy:**

1.  **Identify Sections**: Use regex to isolate the text blocks for `MAIN JOURNALS` and `LOBES`.
2.  **Define Headers**: Establish the expected column headers for each section as they appear in the PDF.
3.  **Map Characteristics**: Create a mapping for `MAIN JOURNALS` from the PDF's header names (e.g., 'Measured Diameter') to your desired `Caracteristica` (e.g., 'Diametro'). For `LOBES`, the PDF headers will be used directly as `Caracteristica`.
4.  **Extract Data Lines**: Iterate through the lines in each section.
5.  **Identify `Apoyo` / `Leva`**: For `MAIN JOURNALS`, identify the `Apoyo` identifier at the start of the line. For `LOBES`, identify the `Leva` identifier (e.g., '1: EXH-1').
6.  **Extract Measurements**: Use regex to extract numerical values and check for the '#' flag.
7.  **Populate `Resultado`**: Assign 'Nok' if '#' is present, otherwise 'Ok'.
8.  **Construct Rows**: Append the extracted data to `data_rows` to build the final DataFrame.
"""

# Este celda ahora muestra el DataFrame consolidado 'df_apoyos_final' de todos los archivos procesados.
# La lógica de extracción y guardado en Excel se ha movido y consolidado en la celda principal de procesamiento (05f915f2).
print("\n--- DataFrame consolidado de 'Apoyos' (primeras 5 filas) ---")
display(df_apoyos_final.head())

"""### Creating 'Levas' Sheet

Now, I will create a new sheet in `data.xlsx` named 'Levas'. This sheet will contain the data extracted from the LOBES section of your PDF, using the specified characteristics.
"""

# Este celda ahora muestra el DataFrame consolidado 'df_levas_final' de todos los archivos procesados.
# La lógica de extracción y guardado en Excel se ha movido y consolidado en la celda principal de procesamiento (05f915f2).
print("\n--- DataFrame consolidado de 'Levas' (primeras 5 filas) ---")
display(df_levas_final.head())

"""### Creando la hoja 'chatter Levas'

Ahora, crearemos una nueva hoja en `data.xlsx` llamada 'chatter Levas'. Esta hoja contendrá los datos extraídos de la sección 'CHATTER:' de tu PDF, utilizando las características y áreas especificadas, e ignorando la columna `@UPR`.
"""

# Este celda ahora muestra el DataFrame consolidado 'df_chatter_lobes_final' de todos los archivos procesados.
# La lógica de extracción y guardado en Excel se ha movido y consolidado en la celda principal de procesamiento (05f915f2).
print("\n--- DataFrame consolidado de 'chatter Levas' (primeras 5 filas) ---")
display(df_chatter_lobes_final.head())

"""### Creando la hoja 'Chatter apoyos'

Ahora, crearemos una nueva hoja en `data.xlsx` llamada 'Chatter apoyos'. Esta hoja contendrá los datos extraídos de la sección 'CHATTER: Journals' de la **segunda página** de tu PDF, utilizando las características y áreas especificadas, e ignorando la columna `@UPR`.
"""

# Este celda ahora muestra el DataFrame consolidado 'df_chatter_apoyos_final' de todos los archivos procesados.
# La lógica de extracción y guardado en Excel se ha movido y consolidado en la celda principal de procesamiento (05f915f2).
print("\n--- DataFrame consolidado de 'Chatter apoyos' (primeras 5 filas) ---")
display(df_chatter_apoyos_final.head())

"""### Creando la hoja 'Master'

Ahora consolidaremos todos los datos extraídos de las secciones 'MAIN JOURNALS', 'LOBES', 'CHATTER: Base Circle', 'CHATTER: Lift Area' y 'CHATTER: Journals' en una única hoja llamada 'Master' en el archivo `data.xlsx`.
"""

# Este celda ahora muestra el DataFrame consolidado 'df_master' de todos los archivos procesados.
# La lógica de extracción y guardado en Excel se ha movido y consolidado en la celda principal de procesamiento (05f915f2).
print("\n--- DataFrame consolidado 'Master' (primeras 5 filas) ---")
display(df_master.head())

"""### Creando la hoja 'Nok'

Ahora, filtraremos el DataFrame `df_master` para incluir solo las filas donde el 'Resultado' sea 'Nok' y guardaremos estos datos en una nueva hoja llamada 'Nok' en el archivo `data.xlsx`.
"""

# Este celda ahora muestra el DataFrame consolidado 'df_nok' de todos los archivos procesados.
# La lógica de extracción y guardado en Excel se ha movido y consolidado en la celda principal de procesamiento (05f915f2).
print("\n--- DataFrame consolidado 'Nok' (primeras 5 filas) ---")
display(df_nok.head())

"""### Creando la hoja 'Análisis'

Ahora, generaremos una hoja de resumen llamada 'Análisis' en `data.xlsx`. Esta hoja contendrá estadísticas clave sobre los datos procesados, incluyendo:

- Número total de piezas analizadas.
- Número de piezas con resultado 'Ok' y 'Nok'.
- Número total de características medidas.
- Número de características con resultado 'Ok' y 'Nok'.
- Un listado de las características 'Nok' más frecuentes, ordenado de mayor a menor.
"""

# Las métricas de resumen y el DataFrame `df_analysis` ahora se calculan en la celda principal (05f915f2).
# La escritura en Excel para 'Analisis_Resumen' también se realiza en la celda 05f915f2.

print("--- Resumen del Análisis ---")
display(df_analysis)

print(f"\nTodos los datos consolidados y guardados en '{output_excel_filename}'")

"""### Análisis Detallado de las 5 Principales Características NOK

A continuación, se presenta un análisis en profundidad para las 5 características que más frecuentemente resultaron en 'Nok', según el conteo previo. Para cada una, se desglosan las ubicaciones específicas (Leva o Apoyo) donde se encontraron fallas, así como estadísticas detalladas de las mediciones.

Analizi segun el tiempo, verificar si funciona de lo contrario eliminarla

### Adaptando el Manejo de Archivos para Streamlit

El código actual en Google Colab utiliza `google.colab.files.upload()` para cargar archivos. Para integrar la lógica de procesamiento de ZIP y PDF en una aplicación de Streamlit, necesitarás reemplazar este método de carga con `st.file_uploader`.

Aquí se muestra cómo puedes adaptar la función de carga de archivos para Streamlit, utilizando la misma lógica de procesamiento de ZIP y PDF que ya tienes implementada. La idea es que el contenido de los archivos subidos por Streamlit (que son bytes) se pase directamente a una versión adaptada de tu función `add_zip_contents`.
"""

!pip install streamlit

import streamlit as st
import io
import zipfile
from pathlib import PurePosixPath

# IMPORTANTE: En tu aplicación real de Streamlit, la función `add_zip_contents`
# (de la celda `KJxpszsuClSl` de Colab) debería estar definida o importada en tu script.
# Aquí, la recreamos de forma anidada para demostrar cómo se integraría.

def streamlit_main_processing():
    st.title("Cargador de Archivos PDF y ZIP")

    st.markdown("Sube tus archivos PDF o ZIP. Los PDFs dentro de los ZIPs serán extraídos automáticamente.")

    uploaded_files_streamlit = st.file_uploader(
        "Selecciona uno o más archivos",
        type=["pdf", "zip"],
        accept_multiple_files=True
    )

    if uploaded_files_streamlit:
        st.write("---")
        st.subheader("Procesando Archivos...")

        # Este diccionario mimicará el diccionario `uploaded` de tu código de Colab,
        # conteniendo los bytes de los PDF indexados por sus nombres.
        processed_pdfs_for_colab_logic = {}
        total_zip_files_detected = 0
        current_ignored_files = []

        # Versión adaptada de `add_zip_contents` para Streamlit
        # con manejo de variables locales y mensajes de Streamlit.
        def _adapt_add_zip_contents_for_streamlit(zip_bytes, source_name="archivo.zip", depth=0):
            nonlocal total_zip_files_detected
            nonlocal processed_pdfs_for_colab_logic # Para modificar el diccionario externo

            # Asumiendo MAX_ZIP_DEPTH es 5, como en tu código original
            if depth > 5:
                st.warning(f"⚠️ Se alcanzó el máximo de ZIP anidados en: {source_name}")
                return

            try:
                with zipfile.ZipFile(io.BytesIO(zip_bytes), "r") as z:
                    for info in z.infolist():
                        if info.is_dir():
                            continue
                        safe_name = str(PurePosixPath(info.filename))
                        suffix = PurePosixPath(safe_name).suffix.lower()

                        try:
                            content = z.read(info)
                        except Exception as e:
                            st.error(f"⚠️ No se pudo leer '{safe_name}' dentro de {source_name}: {e}")
                            continue

                        if suffix == ".pdf":
                            pdf_name = f"{source_name}::{safe_name}"
                            # Manejar nombres duplicados como en la lógica original
                            base_name = pdf_name
                            counter = 2
                            while pdf_name in processed_pdfs_for_colab_logic:
                                stem = PurePosixPath(base_name).stem
                                parent = str(PurePosixPath(base_name).parent)
                                if parent == ".":
                                    pdf_name = f"{stem}_{counter}.pdf"
                                else:
                                    pdf_name = f"{parent}/{stem}_{counter}.pdf"
                                counter += 1
                            processed_pdfs_for_colab_logic[pdf_name] = content
                            st.success(f"  - PDF encontrado: {pdf_name}")
                        elif suffix == ".zip":
                            total_zip_files_detected += 1
                            _adapt_add_zip_contents_for_streamlit(
                                content,
                                source_name=f"{source_name}::{safe_name}",
                                depth=depth + 1
                            )
            except zipfile.BadZipFile:
                st.error(f"⚠️ El archivo '{source_name}' no es un ZIP válido.")
            except Exception as e:
                st.error(f"⚠️ Error procesando ZIP '{source_name}': {e}")


        for uploaded_file in uploaded_files_streamlit:
            file_name = uploaded_file.name
            file_content_bytes = uploaded_file.read() # Obtener el contenido del archivo como bytes

            suffix = PurePosixPath(file_name).suffix.lower()

            if suffix == ".pdf":
                processed_pdfs_for_colab_logic[file_name] = file_content_bytes
                st.success(f"✅ PDF '{file_name}' listo para procesar.")
            elif suffix == ".zip":
                total_zip_files_detected += 1
                st.info(f"📦 Procesando ZIP: '{file_name}'...")
                _adapt_add_zip_contents_for_streamlit(
                    file_content_bytes,
                    source_name=file_name,
                    depth=0
                )
            else:
                current_ignored_files.append(file_name)
                st.warning(f"❌ Archivo '{file_name}' ignorado (tipo no soportado).")

        st.write("--- ")
        st.subheader("Resumen de Carga Final:")
        st.success(f"Total de PDFs listos para procesar: {len(processed_pdfs_for_colab_logic)}")
        st.info(f"Total de ZIPs procesados: {total_zip_files_detected}")

        if current_ignored_files:
            st.error(f"Archivos ignorados: {', '.join(current_ignored_files)}")

        if processed_pdfs_for_colab_logic:
            st.write("Lista de PDFs que serán enviados a la lógica de procesamiento principal:")
            for i, pdf_name in enumerate(processed_pdfs_for_colab_logic.keys(), start=1):
                st.write(f"  - {i}. {pdf_name}")

            st.markdown(
                "**Siguiente paso:** El diccionario `processed_pdfs_for_colab_logic` "
                "contiene todos los PDFs extraídos (tanto individuales como de ZIPs) "
                "en un formato idéntico al diccionario `uploaded` de tu código de Colab. "
                "Puedes pasar este diccionario directamente a tu lógica principal de procesamiento "
                "para generar los reportes."
                "(e.g., la lógica de la celda `05f915f2` que itera sobre `uploaded.keys()`)"
            )
            # Aquí es donde llamarías a tu función principal de procesamiento de PDF.
            # Por ejemplo:
            # df_master, df_nok, df_analysis = your_main_processing_function(processed_pdfs_for_colab_logic)
            # st.dataframe(df_master.head()) # Para mostrar algunos resultados
        else:
            st.warning("No se encontraron PDFs válidos para procesar.")

# Este bloque `if __name__ == '__main__':` es cómo Streamlit ejecuta la aplicación.
# Se incluye aquí para la completitud de la estructura de Streamlit,
# pero no ejecutará una aplicación de Streamlit directamente dentro de Google Colab.
if __name__ == '__main__':
    # Para ejecutar esto en Streamlit, guarda este código en un archivo .py (ej. app.py)
    # y luego ejecuta `streamlit run app.py` desde tu terminal.
    pass

from google.colab import files
import os
import time

# Descargar el archivo principal.
if os.path.exists("data.xlsx"):
    files.download("data.xlsx")
    print("✅ Descarga iniciada: data.xlsx")
else:
    print("⚠️ No se encontró data.xlsx")

# Descargar la segunda parte solo si fue necesaria.
if os.path.exists("data_part2.xlsx"):
    time.sleep(2)
    files.download("data_part2.xlsx")
    print("✅ Descarga iniciada: data_part2.xlsx")